const ProjectsData = [
  {
    id: 1,
    title: 'Blog App',
    description: 'A responsive blogging website using MERN stack. User can post a blog and see it on the website. Users can add image links along with their post, the post also displays time.',
    image: '/projects-img/blog-app.png',
    github: 'https://github.com/singhkailash9/blog-site-react',
    tags: ['React.js', 'Mongoose', 'Express', 'Node', 'Blog'],
  },
  {
    id: 2,
    title: 'Movies App',
    description: 'A movies web app which fetches data from TMDB API. It displays a list of latest release and their description. The movies can be searched using name',
    image: '/projects-img/movies-app.png',
    github: 'https://github.com/singhkailash9/movies-app',
    tags: ['API', 'HTML', 'JavaScript', 'CSS'],
  },
  {
    id: 3,
    title: 'Keeper App',
    description: 'A Keeper App to keep your notes using the MERN stack, inspired by the Google Keeps App.',
    image: '/projects-img/keeper-app.png',
    github: 'https://github.com/singhkailash9/keeper-app-react',
    tags: ['Keeper', 'React.js', 'Mongoose', 'Express', 'Node'],
  },
  {
    id: 4,
    title: 'Wordle Clone',
    description: 'A clone of the popular word puzzle game, Wordle, built using HTML, CSS, and JavaScript.',
    image: '/projects-img/wordle-clone.png',
    github: 'https://github.com/singhkailash9/wordle-clone',
    tags: ['Clone', 'JavaScript', 'Game', 'Wordle'],
  },
  {
    id: 5,
    title: 'Nodot - A discord bot',
    description: 'A multi-featured discord bot using Node.js which can handle both text based and slash based commands.',
    image: '/projects-img/nodot.png',
    github: 'https://github.com/singhkailash9/nodot-discord-bot',
    tags: ['Node.js', 'Discord.js', 'Bot'],
  },
  {
    id: 6,
    title: 'Landing Page',
    description: 'A landing Page for Photo Editing Software',
    image: '/projects-img/landing-page.png',
    github: 'https://github.com/singhkailash9/OIBGRIP-KAILASH',
    tags: ['Homepage', 'JavaScript', 'Frontend'],
  },
  {
    id: 7,
    title: 'Flask REST API',
    description: 'A REST API built using flask library in Python able to do CRUD operations.',
    image: '/projects-img/flask-api.png',
    github: 'https://github.com/singhkailash9/flask-rest-api',
    tags: ['REST', 'Flask', 'Python', 'CRUD'],
  },
];

export default ProjectsData;
