const ProjectsData = [
  {
    id: 1,
    title: 'Movies App',
    description: 'A movies web app which fetches data from TMDB API. It displays a list of latest release and their description. The movies can be searched using name',
    image: '/projects-img/movies-app.png',
    github: 'https://github.com/singhkailash9/movies-app',
    tags: ['API', 'HTML', 'JavaScript', 'CSS'],
  },
  {
    id: 2,
    title: 'Blog App',
    description: 'A responsive blogging website using React.js. User can post a blog and see it on the website. Users can add image links along with their post, the post also displays time.',
    image: '/projects-img/blog-app.png',
    github: 'https://github.com/singhkailash9/blog-site-react',
    tags: ['React.js', 'Responsive', 'Blog', 'CSS', 'HTML'],
  },
  {
    id: 3,
    title: 'Wordle Clone',
    description: 'A clone of the popular word puzzle game, Wordle, built using HTML, CSS, and JavaScript.',
    image: '/projects-img/wordle-clone.png',
    github: 'https://github.com/singhkailash9/wordle-clone',
    tags: ['Clone', 'JavaScript', 'Game'],
  },
  {
    id: 4,
    title: 'Keeper App',
    description: 'A Keeper App to keep your notes, inspired by the Google Keeps App.',
    image: '/projects-img/keeper-app.png',
    github: 'https://github.com/singhkailash9/keeper-app-react',
    tags: ['Keeper', 'React.js', 'Responsive'],
  },
  {
    id: 5,
    title: 'Landing Page',
    description: 'A landing Page for Photo Editing Software',
    image: '/projects-img/landing-page.png',
    github: 'https://github.com/singhkailash9/OIBGRIP-KAILASH',
    tags: ['Homepage', 'JavaScript', 'Frontend'],
  },
  {
    id: 6,
    title: 'To Do List',
    description: 'A to do list to keep track of things using JavaScript',
    image: '/projects-img/todo-js.png',
    github: 'https://github.com/singhkailash9/todoJS',
    tags: ['ToDoList', 'JavaScript', 'VanillaJS', 'WebDevBasics'],
  },
  // {
  //   id: 7,
  //   title: 'Project 7',
  //   description: 'Description of Project 7.',
  //   image: 'project7.jpg',
  //   github: 'https://github.com/username/project7',
  //   tags: ['Node.js', 'Express', 'MongoDB'],
  // },
];

export default ProjectsData;
